"""
backend/api/reflex_playbook.py — RAG corpus + LLM decision engine for the
OrbitMind onboard reflex layer.

The threat *classification* (SCANNING / MONITORING / WARNING / CRITICAL) is kept
deterministic on purpose — a safety reflex should not let an LLM override a
range threshold. The *response* (which play applies, the reasoning narrative,
and the evasion command) is generated by retrieval + an LLM, with a
deterministic guardrail that validates any proposed thruster command and a
rule-based fallback so the reflex never depends on the network.

Pure logic only (no OpenCV/torch imports) so it is unit-testable on its own.
"""

import json
import logging

from backend.content_review import review_reflex_narrative

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# DEMO SCAFFOLDING — force_bad_narrative
# ---------------------------------------------------------------------------
# These constants exist ONLY so a presenter can force the content readiness
# review to reject a narrative live on stage (to show the amber "SAFE
# FALLBACK" pill blocking something). They are never produced by the LLM or
# the rule-based fallback, and are never used unless a caller explicitly
# passes force_bad_narrative=True all the way down from the HTTP layer. The
# narrative below is deliberately malformed for two REAL reasons that
# review_reflex_narrative (backend/content_review.py) will genuinely reject:
# it has no line starting with "Verdict:", and it names the "X" axis while
# the accompanying (also hardcoded) dodge command reports axis "Z".
_DEMO_BAD_NARRATIVE = [
    "Target closing fast; priming reaction-control thrusters along the -X axis.",
    "Command constraint validated successfully.",
]
_DEMO_BAD_DODGE_COMMAND = {
    "intent": "EVADE",
    "axis": "Z",
    "delta_v_cm_s": 12,
    "duration_ms": 400,
    "reason": "demo_scaffolding_forced_rejection",
    "post_evade_action": "schedule_correction_burn",
}

# ---------------------------------------------------------------------------
# RAG corpus — onboard evasion playbook
# ---------------------------------------------------------------------------
EVASION_PLAYS = [
    {
        "id": "scan",
        "name": "Proximity Scan - No Target",
        "applies_when": "no target detected",
        "min_range_m": None,
        "max_range_m": None,
        "action": "Continue proximity scan of the sensor field of view.",
        "command": None,
    },
    {
        "id": "monitor",
        "name": "Normal Operations - Safe Proximity",
        "applies_when": "range > 2.2 m",
        "min_range_m": 2.2,
        "max_range_m": float("inf"),
        "action": "Continue passive tracking. No thruster activity.",
        "command": None,
    },
    {
        "id": "prime",
        "name": "Play 7 - Pre-Collision Evasion Alert",
        "applies_when": "1.5 m <= range <= 2.2 m",
        "min_range_m": 1.5,
        "max_range_m": 2.2,
        "action": "Prime reaction-control thrusters and compute the evasion vector; hold for trigger.",
        "command": None,
    },
    {
        "id": "evade",
        "name": "Play 14 - Autonomous Evasion Protocol",
        "applies_when": "range < 1.5 m",
        "min_range_m": 0.0,
        "max_range_m": 1.5,
        "action": "Execute a cross-track evasion burn on the +Y axis, then schedule a correction burn.",
        "command": {
            "intent": "EVADE",
            "axis": "Y",
            "delta_v_cm_s": 12,
            "duration_ms": 400,
            "reason": "debris_tumbling_close_approach",
            "post_evade_action": "schedule_correction_burn",
        },
    },
]
TOTAL_PLAYS = len(EVASION_PLAYS)

# Safety envelope used by the deterministic guardrail.
THRUSTER_AXES = {"X", "Y", "Z"}
DELTA_V_MIN_CM_S = 1.0
DELTA_V_MAX_CM_S = 50.0

# Range thresholds (m) for the deterministic safety classification.
SAFE_RANGE_M = 2.2
WARNING_RANGE_M = 1.5

# Cache the LLM/fallback narrative per threat band so the LLM is invoked at most
# once per band per process — not on every video frame.
_DECISION_CACHE: dict = {}


def reset_decision_cache() -> None:
    """Clear the per-band decision cache (e.g. when the source video changes)."""
    _DECISION_CACHE.clear()


# ---------------------------------------------------------------------------
# Deterministic safety classification (intentionally rule-based)
# ---------------------------------------------------------------------------
def classify_threat(detected: bool, distance_m: float) -> tuple[str, str]:
    """Map telemetry to (status, threat_level). Status strings are contractual
    with the frontend (SCANNING / MONITORING / WARNING / CRITICAL)."""
    if not detected:
        return "SCANNING", "LOW"
    if distance_m > SAFE_RANGE_M:
        return "MONITORING", "LOW"
    if distance_m >= WARNING_RANGE_M:
        return "WARNING", "AMBER"
    return "CRITICAL", "RED"


# ---------------------------------------------------------------------------
# Decision-Loop Replay — relative range as an explicitly-labeled swept input
# ---------------------------------------------------------------------------
# The benchmark clip never closes to the evasion threshold, so to demonstrate
# the *full* autonomous policy (scan -> monitor -> prime -> evade) we sweep the
# relative range across the bands. This is a demonstration input, NOT a CV
# measurement — detection + decision logic stay live and the UI labels it as a
# swept range. Pure logic kept here so it is unit-testable without torch/OpenCV.
REPLAY_RANGE_FAR_M = 5.0
REPLAY_RANGE_NEAR_M = 0.6


def swept_range(
    frame_idx: int,
    total: int,
    far_m: float = REPLAY_RANGE_FAR_M,
    near_m: float = REPLAY_RANGE_NEAR_M,
) -> float:
    """Linear range ramp ``far_m`` -> ``near_m`` across the clip so the agent
    walks every threat band; the final frames cross ``WARNING_RANGE_M`` into
    CRITICAL/evade."""
    if total <= 1:
        return near_m
    t = max(0.0, min(1.0, frame_idx / (total - 1)))
    return far_m + t * (near_m - far_m)


# ---------------------------------------------------------------------------
# Retrieval (RAG)
# ---------------------------------------------------------------------------
def retrieve_plays(detected: bool, distance_m: float, k: int = 2) -> list[dict]:
    """Rank plays by relevance to the current telemetry (range-band proximity)."""
    if not detected:
        return [p for p in EVASION_PLAYS if p["id"] == "scan"]

    scored: list[tuple[float, dict]] = []
    for p in EVASION_PLAYS:
        lo, hi = p["min_range_m"], p["max_range_m"]
        if lo is None:
            continue
        if lo <= distance_m <= hi:
            d = 0.0
        else:
            d = min(abs(distance_m - lo), abs(distance_m - hi))
        scored.append((d, p))
    scored.sort(key=lambda x: x[0])
    return [p for _, p in scored[:k]]


# ---------------------------------------------------------------------------
# Deterministic guardrail — validate an LLM-proposed thruster command
# ---------------------------------------------------------------------------
def validate_dodge_command(cmd: dict | None) -> dict | None:
    """Clamp/validate a proposed evasion command to the safety envelope.

    Never lets a raw LLM number through as a thruster command.
    """
    if not cmd:
        return None
    axis = str(cmd.get("axis", "Y")).upper()
    if axis not in THRUSTER_AXES:
        axis = "Y"
    try:
        dv = float(cmd.get("delta_v_cm_s", 12))
    except (TypeError, ValueError):
        dv = 12.0
    dv = max(DELTA_V_MIN_CM_S, min(DELTA_V_MAX_CM_S, dv))
    try:
        duration = int(cmd.get("duration_ms", 400) or 400)
    except (TypeError, ValueError):
        duration = 400
    return {
        "intent": "EVADE",
        "axis": axis,
        "delta_v_cm_s": round(dv, 1),
        "duration_ms": duration,
        "reason": str(cmd.get("reason", "debris_close_approach")),
        "post_evade_action": str(cmd.get("post_evade_action", "schedule_correction_burn")),
    }


# ---------------------------------------------------------------------------
# Rule-based fallback (used when no API key or the LLM call fails)
# ---------------------------------------------------------------------------
def _fallback_decision(
    status: str, plays: list[dict], review_reasons: list[str] | None = None
) -> dict:
    content_review = {
        "passed": False,
        "used_fallback": True,
        "reasons": review_reasons if review_reasons is not None else [],
    }
    play = plays[0] if plays else None
    if status == "SCANNING":
        return {"reasoning": ["Verdict: No catalogued target in view. Continuing proximity scan."],
                "dodge_command": None,
                "content_review": content_review}
    if status == "MONITORING":
        return {"reasoning": ["Verdict: Trajectory nominal. No maneuver scheduled."],
                "dodge_command": None,
                "content_review": content_review}
    if status == "WARNING":
        return {"reasoning": ["Verdict: Target approaching danger zone. Priming reaction-control thrusters."],
                "dodge_command": None,
                "content_review": content_review}
    # CRITICAL
    cmd = validate_dodge_command(play["command"] if play else None)
    return {"reasoning": ["Executing Evasion Maneuver...",
                          "Command constraint validated successfully."],
            "dodge_command": cmd,
            "content_review": content_review}


# ---------------------------------------------------------------------------
# DEMO SCAFFOLDING — forced rejection path (see constants above)
# ---------------------------------------------------------------------------
def _demo_bad_decision(status: str, plays: list[dict]) -> dict:
    """Run the real reviewer against the hardcoded bad narrative and assemble
    the same shape reflex_decision would produce on a genuine review failure
    (deterministic fallback content, real rejection reasons attached).

    DEMO SCAFFOLDING — only reachable via force_bad_narrative=True, never
    invoked in normal operation.
    """
    need_cmd = status == "CRITICAL"
    review = review_reflex_narrative(
        list(_DEMO_BAD_NARRATIVE), _DEMO_BAD_DODGE_COMMAND, status, need_cmd
    )
    result = _fallback_decision(status, plays, review_reasons=review.reasons)
    result["content_review"] = {
        "passed": review.passed,
        "used_fallback": True,
        "reasons": review.reasons,
    }
    return result


# ---------------------------------------------------------------------------
# LLM reasoning (Groq) — reuses settings.groq_api_key
# ---------------------------------------------------------------------------
async def _llm_reflex_decision(
    status: str, threat_level: str, detected: bool, distance_m: float,
    translation: list[float], plays: list[dict],
    review_reasons: list[str] | None = None,
) -> dict | None:
    from backend.config import settings
    if not settings.groq_api_key:
        return None
    try:
        from backend.llm import groq_chat

        play_text = "\n".join(
            f"- {p['name']}: {p['action']} (applies when {p['applies_when']})" for p in plays
        ) or "- (no target; continue scanning)"
        need_cmd = status == "CRITICAL"
        cmd_spec = (
            'an object {"axis":"X|Y|Z","delta_v_cm_s":number between 1 and 50,'
            '"duration_ms":number,"reason":string} for the evasion burn'
            if need_cmd else "null (no burn is warranted at this range)"
        )
        prompt = (
            "You are the onboard autonomous reflex agent of a satellite tracking a tumbling "
            "debris object with its camera. Decide the response for the CURRENT telemetry using "
            "ONLY the retrieved playbook entries.\n\n"
            f"Telemetry: target_detected={detected}, range={distance_m:.2f} m, "
            f"translation={[round(t, 2) for t in translation]}, "
            f"threat_level={threat_level}, status={status}.\n\n"
            f"Retrieved playbook (RAG):\n{play_text}\n\n"
            "Respond as JSON with keys:\n"
            '  "reasoning": array of 2-3 short onboard-log lines that justify the chosen play. '
            "End with a line starting \"Verdict:\"; for CRITICAL also include a line starting "
            "\"Executing Evasion\". Do not repeat the play name (it is logged separately).\n"
            f'  "dodge_command": {cmd_spec}.'
        )
        raw = await groq_chat(
            prompt,
            system="You are the onboard autonomous reflex agent of a satellite.",
            json_mode=True,
        )
        if raw is None:
            return None
        data = json.loads(raw)
        reasoning = [str(x) for x in data.get("reasoning", []) if str(x).strip()]
        if not reasoning:
            return None
        dodge = validate_dodge_command(data.get("dodge_command")) if need_cmd else None
        if need_cmd and dodge:
            reasoning.append("Command constraint validated successfully.")

        review = review_reflex_narrative(reasoning, dodge, status, need_cmd)
        if not review.passed:
            logger.warning(
                "Reflex narrative failed content review for band %s: %s",
                status, review.reasons,
            )
            if review_reasons is not None:
                review_reasons.extend(review.reasons)
            return None

        return {
            "reasoning": reasoning,
            "dodge_command": dodge,
            "content_review": {"passed": True, "used_fallback": False, "reasons": []},
        }
    except Exception as e:  # noqa: BLE001 — any LLM failure falls back gracefully
        logger.error("Reflex LLM decision failed: %s", e)
        return None


# ---------------------------------------------------------------------------
# Orchestrator: retrieve -> reason (LLM, cached per band) -> assemble
# ---------------------------------------------------------------------------
async def reflex_decision(
    status: str, threat_level: str, detected: bool, distance_m: float,
    translation: list[float], quaternion: list[float],
    force_bad_narrative: bool = False,
) -> tuple[str, dict | None, dict]:
    """Return (decision_log, dodge_command, content_review) for the current frame.

    The LLM narrative is generated once per threat band and cached; a fresh
    live telemetry header is prepended each frame so the displayed range stays
    current without re-invoking the model. Before the LLM's narrative is
    cached (and therefore before it can be served on every subsequent frame
    in that band) it must pass ``review_reflex_narrative``; a failed review
    causes the LLM result to be discarded in favour of the deterministic
    fallback, and the fallback is cached instead.

    ``force_bad_narrative`` is DEMO SCAFFOLDING (default False): when True,
    the hardcoded ``_DEMO_BAD_NARRATIVE`` is run through the real reviewer to
    produce a genuine, on-stage rejection. This path deliberately bypasses
    ``_DECISION_CACHE`` entirely (no read, no write) so a forced-bad request
    can never contaminate what normal requests for this band see afterwards.
    """
    plays = retrieve_plays(detected, distance_m)

    if force_bad_narrative:
        decision = _demo_bad_decision(status, plays)
        play_name = plays[0]["name"] if plays else "n/a"
        header = [
            f"Search Query: 'debris proximity / range {distance_m:.2f} m'",
            f"Found Play: '{play_name}' (retrieved {len(plays)} of {TOTAL_PLAYS} plays)",
        ]
        decision_log = "\n".join(header + decision["reasoning"])
        return decision_log, decision["dodge_command"], decision["content_review"]

    cached = _DECISION_CACHE.get(status)
    if cached is None:
        review_reasons: list[str] = []
        cached = await _llm_reflex_decision(
            status, threat_level, detected, distance_m, translation, plays,
            review_reasons=review_reasons,
        )
        if cached is None:
            cached = _fallback_decision(status, plays, review_reasons=review_reasons or None)
        _DECISION_CACHE[status] = cached

    play_name = plays[0]["name"] if plays else "n/a"
    header = [
        f"Search Query: 'debris proximity / range {distance_m:.2f} m'",
        f"Found Play: '{play_name}' (retrieved {len(plays)} of {TOTAL_PLAYS} plays)",
    ]
    decision_log = "\n".join(header + cached["reasoning"])
    content_review = cached.get(
        "content_review", {"passed": True, "used_fallback": False, "reasons": []}
    )
    return decision_log, cached["dodge_command"], content_review
